#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/luighi/.local/lib/python3.9/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/luighi/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/mnt/Archivos/Nextcloud/MaestriaPUCP/Thesis/development/neural-signal-processing/data/mearec/cell_models/bbp/mods/x86_64/.libs/libnrnmech.so" "$@"
